package blogreco.hardcorey.com.github;

import org.apache.commons.math.linear.Array2DRowRealMatrix;
/*
 * the blog-blog similarity matrixs generated by this class are all based on doc-word model
 * this can be extended by using many other algorithms processing the doc-word matrix
 */
public abstract class DocWordBlogSimGenerator {

	protected Array2DRowRealMatrix arrayDocWordMtx;
	protected SimMtx blogSimMtx;//the blog similarity matrix
	protected Array2DRowRealMatrix arraySimMtx;//blog-blog similarity matrix

	public DocWordBlogSimGenerator(DocWordMtx docWordMtx) {
		this.arrayDocWordMtx=docWordMtx.getDocWordMtx();
		this.blogSimMtx=new SimMtx();
		this.blogSimMtx.setItemList(docWordMtx.getBlogList());
		int blogSum=docWordMtx.getBlogList().size();
		this.arraySimMtx=new Array2DRowRealMatrix(blogSum, blogSum);
		this.blogSimMtx.setSimMtx(arraySimMtx);

	}

	public abstract void genSimMtx(double[] params) ;

	public SimMtx getSimMtx() {
		return this.blogSimMtx;
	}
}